# Generated by Django 4.2 on 2025-02-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='merchant_request_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='receipt_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
