# Generated by Django 4.2 on 2025-01-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_category_options_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stocked',
            field=models.BooleanField(default=False),
        ),
    ]
