# Generated by Django 4.2 on 2025-01-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_product_stocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stocked',
            field=models.BooleanField(default=True),
        ),
    ]
