# Generated by Django 4.2 on 2025-02-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
        ('order', '0004_alter_order_transactionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transactionID',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='mpesa.mpesatransaction'),
            preserve_default=False,
        ),
    ]
