# Generated by Django 4.2 on 2025-03-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_payment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lipa_mdogo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
